feat: deployment + bindings + tests
filecoin-station/meridian-measure-contract pull request #1
Opened 2023-08-04 13:51 UTC by AmeanAsad

## Changes:
- Added a rust deployment script for the contract. This resolves deployment issues with using the forge CLI and is required for later interaction with the contract using a script. 
    - Enables deployment using a ledger wallet or a local mnemonic secret. 
- Added rust bindings for the Measure contract. 
- Integration tests for measure contract deployment

2023-08-07 09:02 UTC, juliangruber requested changes
👏

2023-08-07 09:02 UTC, juliangruber commented on README.md
> +cd meridian-measure-contract
```suggestion
git clone https://github.com/meridian-ie/measure-contract.git
cd measure-contract
```

2023-08-07 09:02 UTC, juliangruber commented on README.md
> +foundry test
after the setup instructions above, there is no `foundry` binary:

```bash
$ ls ~/.cargo/bin/
anvil		cargo-clippy	cargo-miri	cast		forge		rust-analyzer	rust-gdbgui	rustc		rustfmt
cargo		cargo-fmt	cargo-release	clippy-driver	rls		rust-gdb	rust-lldb	rustdoc		rustup
```

2023-08-07 09:02 UTC, juliangruber commented on README.md
> +To iterate quickly, the  `anvil` network can be used to locally develop. Note that Anvil strictly uses Etheruem addressing and does not include Filecoin Pre-compiles.
```suggestion
To iterate quickly, the  `anvil` network can be used to develop locally. Note that Anvil strictly uses Etheruem addressing and does not include Filecoin pre-compiles.
```

2023-08-07 09:02 UTC, juliangruber commented on README.md
> +To iterate quickly, the  `anvil` network can be used to locally develop. Note that Anvil strictly uses Etheruem addressing and does not include Filecoin Pre-compiles.
Could you please add some context to the note: Why does knowing the difference matter?

2023-08-07 09:02 UTC, juliangruber commented on README.md
> +First run `anvil` by running:
```suggestion
First run `anvil`:
```

2023-08-07 09:02 UTC, juliangruber commented on README.md
> +forge create --rpc-url http://127.0.0.1:8545 --mnemonic "test test test test test test test test test test test junk" src/Measure.sol:Measure
Getting this:

```
$ forge create --rpc-url http://127.0.0.1:8545 --mnemonic "test test test test test test test test test test test junk" src/Measure.sol:Measure
[⠊] Compiling...
[⠃] Compiling 25 files with 0.8.21
[⠒] Solc 0.8.21 finished in 1.89s
Compiler run successful!
Error: 
No arguments provided for contract constructor. Consider --constructor-args or --constructor-args-path

Context:
- Error #0: Failed to deploy contract
- Error #1: Invalid data
```

2023-08-07 09:02 UTC, juliangruber commented on .gitignore
> +**/**/target
```suggestion
**/**/target

```

2023-08-07 09:02 UTC, juliangruber commented on .github/workflows/contracts.yaml
> +          solc-version: 0.8.21
```suggestion
          solc-version: 0.8.21

```

2023-08-07 09:02 UTC, juliangruber commented on README.md
> +    export TEST_CONTRACT_ADDRESS={this can be an empty string}
```suggestion
export TEST_RPC_URL=https://api.calibration.node.glif.io/rpc/v1
export TEST_MNEMONIC={insert wallet mnemonic here}
export TEST_CONTRACT_ADDRESS={this can be an empty string}
```

2023-08-07 09:02 UTC, juliangruber commented on contract-utils/src/lib.rs
> +    pub async fn deploy_factory_contract<S: Middleware + 'static>(
Is this method named correctly? What factory contract is in use here?

2023-08-07 09:02 UTC, juliangruber commented on foundry.toml
> +calibration = "https://api.calibration.node.glif.io/rpc/v1"
```suggestion
calibration = "https://api.calibration.node.glif.io/rpc/v1"

```

2023-08-07 09:02 UTC, juliangruber commented on src/Measure.sol
nice!

2023-08-07 16:27 UTC, AmeanAsad commented on README.md
> +forge create --rpc-url http://127.0.0.1:8545 --mnemonic "test test test test test test test test test test test junk" src/Measure.sol:Measure
I updated the docs for this on read me but just curious, what version of forge are you running. `forge --version`

2023-08-07 16:27 UTC, AmeanAsad commented on README.md
> +foundry test
Resolved, it should be `forge test` and not `foundry`

2023-08-08 08:18 UTC, juliangruber commented on README.md
> +forge test
```
$ forge test
[⠢] Compiling...
No files changed, compilation skipped

No tests found in project! Forge looks for functions that starts with `test`.
```

Is this expected?

2023-08-08 08:18 UTC, juliangruber commented on README.md
> +forge create --rpc-url http://127.0.0.1:8545 --mnemonic "test test test test test test test test test test test junk" src/Measure.sol:Measure
```bash
$ forge --version
forge 0.2.0 (9a4bb7f 2023-08-07T08:45:10.666329000Z)
```

2023-08-08 08:18 UTC, juliangruber commented on README.md
> +0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
```suggestion
forge create --rpc-url http://127.0.0.1:8545 --mnemonic "test test test test test test test test test test test junk" src/Measure.sol:Measure --constructor-args 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
```

2023-08-08 08:18 UTC, juliangruber commented on README.md
> +0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
otherwise it's invalid shell syntax. If you would like to have it multiline, you can add a `\` before the newline

2023-08-08 08:54 UTC, AmeanAsad commented on README.md
> +forge test
Yes, even though we have a test directory, it doesn't have any functions that run tests.

2023-08-08 09:01 UTC, juliangruber approved these changes

2023-08-09 14:29 UTC, merged